### ISSUE TITLE
Stack Overflow error

### ISSUE THREAD

**Issue by junoon53** [allenai/openie-standalone#28]
I encountered the a stack overflow exception while processing a long file. 
[output_8_Aug_2017.txt](https://github.com/allenai/openie-standalone/files/1209901/output_8_Aug_2017.txt)

**Comment by jkinkead** [comment]
What heap size are you running with?

Have you tried increasing it?

**Comment by junoon53** [comment]
I set the -Xmx10G option in build.sbt before building, and I run sbt with the following command: 

sbt "runMain edu.knowitall.openie.OpenIECli --input-file $1 --output-file $2 --split --ignore-errors --format column" -Xmx5G

My input file is 529010 lines

**Comment by jkinkead** [comment]
This project is set to [fork a new JVM process when running code](https://github.com/allenai/openie-standalone/blob/05ec5296c8460e394bd9abe2122bbc2fe2e6ed19/build.sbt#L79), so setting the sbt heap will not increase the memory available to OpenIE run from sbt.

Try updating [this line](https://github.com/allenai/openie-standalone/blob/05ec5296c8460e394bd9abe2122bbc2fe2e6ed19/build.sbt#L75) to the desired max heap size.

**Comment by junoon53** [comment]
I updated that line to -Xmx20G. Then I ran 'sbt compile'.

I still get the same error. What do you think the problem could be?

**Comment by jkinkead** [comment]
Note that the `javaOptions` setting adjusts the `sbt run` command, not the `sbt compile` command. Also, you need to restart sbt in order to see any changes to the configuration files.

I'm not certain what your problem is at this point. If you're able to reproduce with a simple input, or provide the exact commands & local changes you've made to run this, I might have more ideas.

**Comment by jkinkead** [comment]
Also, that stack overflow error looks a lot like you have some degenerate / incorrect UTF-8 characters in your input.
